### ISSUE TITLE
Save feature not working

### ISSUE THREAD

**Issue by Luigimeansme** [wooferzfg/tww-rando-tracker#10]
I had to take a break from the randomizer for a bit, so I saved my progress on the tracker and closed the tab. When I came back later, I discovered that the tracker was back to square one, as if I hadn't touched it at all. I don't know if the load button is just missing, or it's supposed to load apon coming back to the page, and it didn't, but something is wrong here

**Comment by wooferzfg** [comment]
did you click on "Load Most Recent"?

**Comment by Luigimeansme** [comment]
There's no button that says "Load Most Recent" 
![screenshot 2018-09-16 at 5 56 43 pm](https://user-images.githubusercontent.com/43101156/45602835-e7a21100-b9d9-11e8-8971-3e7ecd9df53a.png)

**Comment by wooferzfg** [comment]
The button is on the launcher page, not the tracker page.

**Comment by Luigimeansme** [comment]
Thank you. My friend sent this to me, so I didn't know there was a launcher. I appreciate the help
