### ISSUE TITLE
Some Earth Temple key counts are incorrect

### ISSUE THREAD

**Issue by octylFractal** [wooferzfg/tww-rando-tracker#1169]
It seems like most of the ET key counts are wrong, as only 1 small key is needed for `Chest In Three Blocks Room`, `Chest Behind Statues`, and `Casket in Second Crypt`; and only 2 small keys are needed for `Stalfos Mini-Boss Room`. There might be more, this is what I discovered while playing through the randomizer.

**Comment by wooferzfg** [comment]
The tracker uses the randomizer's logic. These locations require more keys to prevent softlocking if you use a key on the wrong door.
