### ISSUE TITLE
I'm having this error when importing/loading save: Could not parse requirement: Can Access Item Location "Outset Island - Savage Labyrinth - Floor 30"

### ISSUE THREAD

**Issue by MichaelD0** [wooferzfg/tww-rando-tracker#1305]
Like title says i exported my tracker save and reimported it the next day but it fails with that error message. I'll include error message from localhost but same error with the online version. I'm including the exported JSON.

**JSON**
[tww_rando_tracker_progress(2).json](https://github.com/wooferzfg/tww-rando-tracker/files/14469816/tww_rando_tracker_progress.2.json)

**ERROR**
Could not parse requirement: Can Access Item Location "Outset Island - Savage Labyrinth - Floor 30"
_itemsRemainingForRequirement@http://localhost:8080/bundle.js:60466:13
./node_modules/memoizee/lib/configure-map.js/module.exports/memoized<@http://localhost:8080/bundle.js:29537:44
_isRequirementMet@http://localhost:8080/bundle.js:60451:33
isItemTrue@http://localhost:8080/bundle.js:60350:25
./src/services/boolean-expression.js/evaluate/handleAnd/<@http://localhost:8080/bundle.js:59386:38
arrayEvery@http://localhost:8080/bundle.js:18770:116
every@http://localhost:8080/bundle.js:22768:183
handleAnd@http://localhost:8080/bundle.js:59382:64
_map@http://localhost:8080/bundle.js:59470:16
evaluate@http://localhost:8080/bundle.js:59380:19
_areRequirementsMet@http://localhost:8080/bundle.js:60348:27
isLocationAvailable@http://localhost:8080/bundle.js:60321:19
./node_modules/memoizee/lib/configure-map.js/module.exports/memoized<@http://localhost:8080/bundle.js:29537:94
./src/services/logic-calculation.js/locationCounts/<@http://localhost:8080/bundle.js:60196:37
arrayEach@http://localhost:8080/bundle.js:18753:121
forEach@http://localhost:8080/bundle.js:22949:101
locationCounts@http://localhost:8080/bundle.js:60194:53
./node_modules/memoizee/lib/configure-map.js/module.exports/memoized<@http://localhost:8080/bundle.js:29537:94
chestsCounter@http://localhost:8080/bundle.js:66796:41
render@http://localhost:8080/bundle.js:66978:167
finishClassComponent@http://localhost:8080/bundle.js:40225:145
updateClassComponent@http://localhost:8080/bundle.js:40217:222
beginWork@http://localhost:8080/bundle.js:40611:871
callCallback@http://localhost:8080/bundle.js:37709:119
invokeGuardedCallbackDev@http://localhost:8080/bundle.js:37729:45
invokeGuardedCallback@http://localhost:8080/bundle.js:37750:126
beginWork$1@http://localhost:8080/bundle.js:41677:22
performUnitOfWork@http://localhost:8080/bundle.js:41493:270
workLoopSync@http://localhost:8080/bundle.js:41479:47
renderRootSync@http://localhost:8080/bundle.js:41475:159
performConcurrentWorkOnRoot@http://localhost:8080/bundle.js:41314:166
workLoop@http://localhost:8080/bundle.js:53265:46
flushWork@http://localhost:8080/bundle.js:53243:18
performWorkUntilDeadline@http://localhost:8080/bundle.js:53480:25

**Comment by MichaelD0** [comment]
actually i noticed the website is different so my guess is there was an update to the structure of settings and it invalidates older JSONs. So i think the new update isn't retro compatible with previous saves

**Comment by wooferzfg** [comment]
I don't maintain code to handle older updates, since that would be too much work. You should just use the latest version of the randomizer (currently 1.10)
