### ISSUE TITLE
Add Support for Wind Waker HD Randomizer

### ISSUE THREAD

**Issue by Founntain** [wooferzfg/tww-rando-tracker#1378]
The WWHD Randomizer dropped a couple of days ago and it would be great if the tracker could support it as well. The WWHD Desktop Client has an build in tracker for WWHD, however when not having the desktop installed I usually use this wind waker tracker. It just confuses a bit, because of a bit of different logic, like Tower of the gods being more open than in SD.

If no plans are for it, that is fine as well. It still can be used fine, you just have to keep track of those locations that the SD tracker thinks are not accessible

**Comment by wooferzfg** [comment]
I'm not planning to do this. I assume the quickest route to getting this working would be porting the tracker that's in the desktop client to the web.

**Comment by Founntain** [comment]
> I'm not planning to do this. I assume the quickest route to getting this working would be porting the tracker that's in the desktop client to the web.

Thank you for explaining @wooferzfg appreaciate it, your tool works nonetheless great with the HD Rando.
