### ISSUE TITLE
[Suggestion] Export/Import progress to a file for easier portability.

### ISSUE THREAD

**Issue by Thedrummonger** [wooferzfg/tww-rando-tracker#16]
It would be awesome if you could export your progress to file and then be able to load that file at a different time or location. As someone who plays this casually it would be really convenient to be able to say, move your progress to a different computer or even have multiple randomizer files saved at once. I apologize if this feature already exists but I couldn't seem to find it anywhere.

Thanks!

**Comment by Alkaris** [comment]
I would second this, it be really useful, maybe export as JSON file which can then later be used to import. Seems bit pointless to have the Auto-Save if it doesn't save progress for being accessed later.

**Comment by wooferzfg** [comment]
This feature is done, but it won't be available on https://wooferzfg.me/tww-rando-tracker until Wind Waker Randomizer 1.7 is released.
