### ISSUE TITLE
Merge the Speedrun Branch with Master

### ISSUE THREAD

**Issue by tanjo3** [wooferzfg/tww-rando-tracker#234]
The main difference between these two branches is the sphere logic. I don’t see why that functionality can’t be brought over to the master branch. If you want to hide the spheres for casual runners, a toggle switches for the spheres seem straightforward.

**Comment by wooferzfg** [comment]
Maps and compasses are a significant difference as well.

**Comment by tanjo3** [comment]
Yeah, that's true. Is there a particular reason why those and the spheres exist only in the speedrun branch? As a aside, another reason to combine the two is because, while simple, it's not obvious how to access the speedrun version.

**Comment by wooferzfg** [comment]
I'll remove the speedrun branch within the next week or so. The speedrun branch will remain tagged: https://github.com/wooferzfg/tww-rando-tracker/tree/speedrun-legacy
