### ISSUE TITLE
Separate Charts Tracking from Sea Chart

### ISSUE THREAD

**Issue by tanjo3** [wooferzfg/tww-rando-tracker#235]
Currently, charts are tracked by clicking the little chart icon in the top-left of each quadrant in the sea chart. However, when the user clicks on an island in the sea chart to reveal checks, these icons go away. While this is fine in casual play, if the user wishes for sphere logic to maintain through sunken treasure, the user must identify which chart leads to which island immediately after clicking the location where they had found the chart. This is extremely cumbersome in the current implementation (and also currently not functional, see #57).

My suggestion would be to move charts tracking from the sea charts to its own interface. In that interface, the user could track that they had found Treasure Chart 17 before they had to check where it leads. This is particularly useful when charts are randomized and for Triforce charts which required deciphering before their location is revealed. Once the user links the sunken treasure location to the chart number, the spheres would follow from that. Thus, the user no longer must remember where they had found the chart or are not required to immediately open charts upon finding them. Since this interface would be independent of the state of the sea chart, it would also address #57.

**Comment by wooferzfg** [comment]
Resolved in #765
