### ISSUE TITLE
Dragon Roost Island - Chest on Top of Boulder requirements

### ISSUE THREAD

**Issue by willmtemple** [wooferzfg/tww-rando-tracker#26]
The tracker that's online right now says Chest on Top of Boulder has no requirements, but it should be `(bow | bombs | boomerang | baitbag)` I think. It's also pretty easy to get it with leaf but I don't think that's in logic.

![image](https://user-images.githubusercontent.com/666532/60062941-5d997e00-96b8-11e9-8b2c-5a063df8a4e0.png)

**Comment by willmtemple** [comment]
Sorry I didn't realize I had accidentally ticked bait bag in the shot above and was just seeing "None" in requirements.

**Comment by wooferzfg** [comment]
Items that you start with don't show up as a requirement. I'm still not sure if I want to keep that or not.

**Comment by Xiarno** [comment]
Why bombs?
How do you make it go down with only bombs?

**Comment by wooferzfg** [comment]
@Xiarno You use the boat's cannon to shoot the bomb flowers.

**Comment by Xiarno** [comment]
> @Xiarno You use the boat's cannon to shoot the bomb flowers.

Omg wow. I'm so dumb. You're right.
Funny I know a lot of places so that I can avoid using the bomb cannon but the one place that I could use it I just.... wow.
Well thanks for the help ahah.
