### ISSUE TITLE
Add ability to select caves from clicking the entrance on the map.

### ISSUE THREAD

**Issue by river58** [wooferzfg/tww-rando-tracker#27]
Right now for randomized caves/dungeons and such, you select the cave you were on the map and then select where you entered from. This is all fine and dandy but on the map, it shows the cave on the island you've never checked as crossed off, and can get confusing as theres no real marker on the map directly that shows you havent checked that islands cave entrance. Instead you have to click view entrance. Maybe instead it should be selecting the entrance on the map, and then selecting the actual cave it led into on the selection screen. And then you go into that island and check off the cave, but there's still a red X denoting you havent checked that entrance. Or have this be an extra option maybe.

Edit: Another idea, maybe both of these combined? Both an icon to say you entered the cave there, and an icon showing the entrance there?

**Comment by wooferzfg** [comment]
The current design basically boils down to "exits are more important than entrances". It's far more common to look up which entrance leads to an exit than it is to look up which exit an entrance leads to. It's also a bit easier from a logistical perspective - we can show each entrance as unavailable/available/checked similar to normal locations.

I understand that the process for checking an entrance is pretty unintuitive, but I think the other benefits we get from keeping the UI this way are more important.

**Comment by wooferzfg** [comment]
Planning to implement it this way: https://github.com/wooferzfg/tww-rando-tracker/issues/270#issuecomment-1855025432
