### ISSUE TITLE
Option to toggle between viewing entrances vs. viewing exits

### ISSUE THREAD

**Issue by Crain-32** [wooferzfg/tww-rando-tracker#270]
"View Entrances" could have a toggleable option that would swap you to a "map" view. Pretty much a 7x7 grid that would have red/green circles, or 1/2 circles for Pawprint, the represent if an entrance is in/out of logic. On selection it would turn gray. This would be easier/faster for people who don't have the island names memorized. A back arrow could be placed into the bottom right, as there is no entrance there.

**Comment by wooferzfg** [comment]
I'm thinking that the "View Entrances" button could change all the X/checkmarks (which show exits) into some indicator of the entrances. Then you could hover over each entrance to either see where it leads or to view its requirements. Ideally, you'd also be able to click on an entrance and track its exit.
