### ISSUE TITLE
Clear All Option on FF and TotG Sectors

### ISSUE THREAD

**Issue by tanjo3** [wooferzfg/tww-rando-tracker#279]
When Race Mode is on and there are progress locations in either the Forsaken Fortress or the Tower of the Gods sectors, a Clear All option will be available. Clicking on this clears all progress locations in those respective dungeons. This option is erroneously present.

Steps to reproduce:
1. Launch a tracker with Dungeons, Sunken Treasure (From Treasure Charts), and Race Mode.
2. Click the Forsaken Fortress sector to bring up the Sunken Treasure progress location for Forsaken Fortress.
3. Observe the Clear All button.
4. Click the button and observe that all progress location in the Forsaken Fortress dungeon are then checked off.

Steps are analogous for Tower of the Gods.

**Comment by wooferzfg** [comment]
Fixed in https://github.com/wooferzfg/tww-rando-tracker/commit/12995629ade84b0cd8c075e8ea1333b18369a7bb
