### ISSUE TITLE
Treasure/Triforce Chart Checklist

### ISSUE THREAD

**Issue by pholtos** [wooferzfg/tww-rando-tracker#28]
Basically have a section in the tracker that would make it slightly less troublesome to find which coordinate a chart went to, or otherwise labeling numerically on the tracker which chart goes with which coordinate. Naturally this wouldn't help for randomized charts, but otherwise would speed things up a little.

**Comment by wooferzfg** [comment]
Resolved in #765

**Comment by wooferzfg** [comment]
This should be easier to implement now that #765 is done. When randomized charts are off, we could add a tooltip to each chart in the chart list that shows which island it leads to.
