### ISSUE TITLE
Load from File not working anymore

### ISSUE THREAD

**Issue by Luigimeansme** [wooferzfg/tww-rando-tracker#283]
Just the other day my friend and I started doing a run of this but we learned the hard way that exporting the progress as a json and loading that file isn't working. The settings copy over properly, but the items and locations are all wiped clean as if it's starting a new tracker. Hopefully this can be ironed out soon.

**Comment by wooferzfg** [comment]
This was fixed in https://github.com/wooferzfg/tww-rando-tracker/commit/8cd13925016aa731f7da49d46c10959ccfdd7e1d

You might need to refresh your tracker with Shift + F5. However, if you created a save file a few days ago, that save file will unfortunately not work.
