### ISSUE TITLE
Locations Remaining matches Locations Available, still have 1 thing unavailable.

### ISSUE THREAD

**Issue by pholtos** [wooferzfg/tww-rando-tracker#29]
Ended up in a situation where I have 36 available and 36 remaining, but a location on the map was still red, being a triforce chart. Clicking it to be available made my locations accessible 37 and locations remaining remain at 36.

[Here's a link to the exported progress.](https://www.mediafire.com/file/l91cymh01ejvubi/tww_rando_tracker_progress.json/file)

**Comment by wooferzfg** [comment]
Fixed in https://github.com/wooferzfg/tww-rando-tracker/commit/1f77abcb10a403654933a55be794852bea2077c0

To fix it on your tracker, you just need to check & then uncked the "Defeat Ganondorf" location.
