### ISSUE TITLE
[Suggestion] Tingle Tuner for bombs

### ISSUE THREAD

**Issue by TheMerfox** [wooferzfg/tww-rando-tracker#31]
Some chests, like destroying cannons on lookout towers or the rock spire island cave, can be obtained by using the tingle bombs, but the tracker doesn't recognize the tingle tuner as a possible item to access those. Having a toggle at the start to allow for the tuner items to be counted would be helpful.

**Comment by wooferzfg** [comment]
Tingle bombs can be used to destroy those, but the randomizer doesn't have that in the logic. The tracker will always follow the randomizer's logic.
