### ISSUE TITLE
Tooltip for Letter Triggers

### ISSUE THREAD

**Issue by Phlosioneer** [wooferzfg/tww-rando-tracker#36]
Some of the letters have different triggers than the vanilla game, and the list of prerequisites is not always sufficient. For example, Tingle's letter is only sent after you've beaten the Helmroc King, but there's no way to know that from the tracker.

When letters require another location to be checked, they should list that in their required items list. These are the letters with location requirements:
- Letter from Baito: `Defeated Jalhalla (Earth Temple)`
- Letter from Orca: `Defeated Kalle Demos (Forbidden Woods)`
- Letter from Aryll: `Defeated Helmroc King (Forsaken Fortress)`
- Letter from Tingle: `Defeated Helmroc King (Forsaken Fortress)`

I don't think these need to be actual requirements in the logic. It's fine to list them as an available location. But it saves newer users a lot of headache to know what triggers them.

**Comment by Phlosioneer** [comment]
I looked through the code a bit. It seems that the main problem is that the item_locations.txt doesn't distinguish between "can access X" and "has beaten boss to access X".

For example, the letter from orca says:
```
Mailbox - Letter from Orca:
  Need: Can Access Other Location "Forbidden Woods - Kalle Demos Heart Container"
  # Note: In the vanilla game, this letter is sent after you watch a cutscene on Greatfish Isle.
  # But since that's impossible when cutscenes are removed, the randomizer changes it to be sent when you kill Kalle Demos.
```
Then the tracker's logic takes the "can access other location" and reduces it to the requirements to fight kalle demos.

There are two solutions that I can see right now. Option one is to add a dummy requirement to the variables for beating FW, FF, and ET. These requirements will be "given" from the start. Then, we tweak the Need expressions for each of the letters to append " & Beaten <dungeon name>". That will then appear to the player correctly in the tooltip list.

Option two is to add a new expression; instead of "can access", these letters really care about "**has** accessed". This way, the letters will not appear available to the user until they actually check off the boss's heart container item.

**Comment by wooferzfg** [comment]
https://github.com/wooferzfg/tww-rando-tracker/pull/38
