### ISSUE TITLE
Required Items to get Forsaken Fortress Chests 

### ISSUE THREAD

**Issue by Jritch725** [wooferzfg/tww-rando-tracker#39]
You can get the chests for Forsaken Fortress without the skull hammer. While you can't get anywhere from the closest wooden door, you can use the Deku leaf to glide to the other door. From there, you can get the chest on the bed, and go around the top of the fortress to bypass anyplace you would need the skull hammer.

**Comment by wooferzfg** [comment]
The logic in the tracker is entirely determined by the logic in the randomizer. If you want, you can file an issue there: https://github.com/LagoLunatic/wwrando/issues
