### ISSUE TITLE
wrong requirements 

### ISSUE THREAD

**Issue by mattattacknega** [wooferzfg/tww-rando-tracker#415]
I'm using the online version of the tww-rando-tracker but I'm noticing a few location were it says you need the grappling hook but you don't. So far I have found this with Orca - Give 10 Knight's Crests and Maggie's Father - Give 20 Skull Necklaces and while I haven't found enough joy pendants yet for Mrs. Marie I assume this is also the case for her and I only just noticed now but it says you need the grappling hook for give 15 green chu jelly to the chu jelly shop but I'm pretty sure that's also wrong.

**Comment by wooferzfg** [comment]
The tracker's logic uses the randomizer's logic. The randomizer requires the Grappling Hook for these locations because it makes farming spoils much easier.
