### ISSUE TITLE
Forsaken Fortress 

### ISSUE THREAD

**Issue by Rixuous** [wooferzfg/tww-rando-tracker#43]
In the Forsaken Fortress, it is marked that you cannot get to the 'Chest Outside Upper Jail Cell' without either the hook-shot or the leaf, but getting caught by the Floormaster in the middle room with the hanging boat will throw you in the upper jail cell, which you can then proceed to escape from and grab the chest. So technically it is possible to get this as soon as you get the hammer and bombs. I ended up figuring this out after finding it had the item I needed in the spoiler log, with nowhere else to go.

**Comment by wooferzfg** [comment]
The logic in the tracker is entirely determined by the logic in the randomizer. If you want, you can file an issue there: https://github.com/LagoLunatic/wwrando/issues

**Comment by Rixuous** [comment]
Will do, I didn't know that's how it worked, haha
