### ISSUE TITLE
Mirror shield not listed as requirement.

### ISSUE THREAD

**Issue by Nevik9191** [wooferzfg/tww-rando-tracker#46]
When you go to select a cave entrance result on the map angular cave is not listed as having a mirror shield requirement. It only lists it as a requirement on the actual angular cave.

![mirror shield](https://user-images.githubusercontent.com/23410655/72044834-ab975d00-3269-11ea-9cdb-02de9c629778.PNG)

**Comment by wooferzfg** [comment]
The Mirror Shield isn't required to enter that cave.

**Comment by Nevik9191** [comment]
Sorry turns out I'm really dumb and I don't understand how the tracker worked sorry about that. I feel quite embarrassed.
