### ISSUE TITLE
Wrong item requirements for "Enemy Platforms"

### ISSUE THREAD

**Issue by alkaris2** [wooferzfg/tww-rando-tracker#491]
I've noticed there is wrong item requirements for some Defeat Enemy Platforms, particularly the ones with Wizrobes on them. Islet of Steel Platforms for Defeat the enemy platforms says you can use Hookshot to defeat Wizrobes, but you cannot do that, Hookshot only stun locks them, same with Boomerang.

**Comment by wooferzfg** [comment]
The item requirements are taken directly from the randomizer logic - please report any issues there - https://github.com/LagoLunatic/wwrando/issues
