### ISSUE TITLE
Speedrun Tracker for 1.7

### ISSUE THREAD

**Issue by MrPogostyc** [wooferzfg/tww-rando-tracker#50]
I'm not sure but from my knowledge, there has not been an update for the speedrun version of the tracker for 1.7. If there is an updated version, can i get a link? Thanks for your epicness.

**Comment by wooferzfg** [comment]
The speedrun version hasn't been updated yet because the tournament is still ongoing and that uses version 1.6. I'll update to 1.7 after the tournament is over.
