### ISSUE TITLE
Getting to Forbidden Woods without grappling hook

### ISSUE THREAD

**Issue by gg30433043** [wooferzfg/tww-rando-tracker#53]
With just the Deku leaf and the Magic upgrade, you can make it to forbidden woods entrance without grappling hook. Tracker says otherwise
![image](https://user-images.githubusercontent.com/14061489/79783937-780baa80-830f-11ea-81c7-71b37956d129.png)

**Comment by gg30433043** [comment]
Apologies forgot to label

**Comment by wooferzfg** [comment]
The tracker's logic is based on the randomizer's logic. The randomizer assumes you need the Grappling Hook because skipping it is not obvious to casual players.
