### ISSUE TITLE
Tracker incorrectly displaying items from Seed

### ISSUE THREAD

**Issue by yulayula16** [wooferzfg/tww-rando-tracker#54]
I just recently started up a new Wind Waker Randomizer with the latest update, and when I entered the Seed Permalink for it into the tracker, I found it to be incorrectly displaying items that I don't have from the start, or not selected items that I have from start.

![Shutter__2020-04-25__08_23_00_AM](https://user-images.githubusercontent.com/60402017/80262959-45c2ca00-86ce-11ea-8086-a6e938380c0b.png)

My randomizer Item Starter settings has the following items;

- Telescope
- Tingle Tuner
- Magic Armor
- Progressive Bomb Bag 1
- Progressive Bomb Bag 2
- Progressive Wallet 1
- Progressive Wallet 2
- Progressive Quiver 1
- Progressive Quiver 2

the tracker as shown in the image before you there doesn't have those listed as I've got there, and marks that I have Magic Upgrade and Bait Bag, which clearly isn't and is in the randomizer pool like all the other items are. Also the Randomizer seed is set to have 4 Triforce Pieces at the start, the tracker also doesn't recognise this either and instead shows a blank Triforce for no pieces collected.

![Shutter__2020-04-25__08_30_56_AM](https://user-images.githubusercontent.com/60402017/80263229-22e4e580-86cf-11ea-93c7-6df8b251d096.png)

![Shutter__2020-04-25__08_48_20_AM](https://user-images.githubusercontent.com/60402017/80263953-8ff97a80-86d1-11ea-878b-67812641ca33.png)

Also why was Sword + Sword Upgrades as well as Great Spin removed from the Tracker?

My complaints with this tracker, while it's decent, its by no means 100% that great, for one the tracker backgrounds for one, especially for items, would be better if it didn't have Textured Backgrounds, even when I turn on Single Color Background, there's still that textured background on things like the Triforce and the Pearls, which doesn't work if you're displaying this for Streams or videos and you want to Green Screen the backgrounds to fit on a different background. It doesn't look clean when it can't be Color Keyed correctly using a color like `#00ff00` which is color key specific for Green Screens. I usually manually edit CSS with my own modification overrides of the default Green Background color to that color specifically to color key that background out for displaying on streams.

The other tracker parts backgrounds are fine, no issues with those really. I don't need to Color Key those.

**Comment by wooferzfg** [comment]
The tracker currently only supports version 1.7 of the Wind Waker Randomizer. The issue to add support for the newest changes on the `master` branch is here: https://github.com/wooferzfg/tww-rando-tracker/issues/52

**Comment by yulayula16** [comment]
This is version 1.7, specifically version `1.7.0_366e3de` of the randomizer that I used as of update from 12 days ago.

**Comment by wooferzfg** [comment]
1.7 is available for download here: https://github.com/LagoLunatic/wwrando/releases/download/1.7.0/Wind_Waker_Randomizer_1.7.0_64bit.zip

The version you're using is newer.

**Comment by yulayula16** [comment]
No it's not, and that's for Windows, I don't use that.

**Comment by wooferzfg** [comment]
If you're running from soure, version 1.7 is tagged: 
 https://github.com/LagoLunatic/wwrando/tree/1.7.0
