### ISSUE TITLE
Hide soft requirements in the tracker

### ISSUE THREAD

**Issue by Alivent** [wooferzfg/tww-rando-tracker#7]
Several Mailbox Letters are listed as requiring song of passing even though just sailing and letting the day pass gives you the letter perfectly fine

**Comment by wooferzfg** [comment]
The tracker uses the same logic as the randomizer. I think the tracker will stay like this until some sort of solution based on separating "soft" and "hard" requirements is figured out.

**Comment by wooferzfg** [comment]
Looks like Song of Passing will be a starting item in the next version, which makes this less of an issue.
