### ISSUE TITLE
Islet of Steel Requirements Error

### ISSUE THREAD

**Issue by livipup** [wooferzfg/tww-rando-tracker#792]
Hi. I noticed that the map tracker says you need bombs to get the Islet of Steel's interior chest. This makes sense, but you don't actually need bombs because you can stay close to the ship in the entrance and let the other ships hit it with bombs. This is true for all similar treasures as well. I forget what part of the map, but I recall in another part there was a special-looking ship with two other normal ones and I did the same thing to get the treasure from that one.

**Comment by wooferzfg** [comment]
The tracker's requirements are based directly on the randomizer's logic. Bombs are included as a requirement to be more friendly towards casual players.
