### ISSUE TITLE
Open tracker in new tab option

### ISSUE THREAD

**Issue by Samutz** [wooferzfg/tww-rando-tracker#844]
Please add an option to open the tracker in a tab instead of a new window.

**Comment by wooferzfg** [comment]
Opening the tracker in a new window allows it to be the correct size when it opens. If you'd like to open the tracker in a new tab, the easiest thing to do is to just copy the URL from the new window, and paste it in the new tab page. I'd like to avoid adding extra buttons to the launcher page just for this.
