### ISSUE TITLE
Tracker oddity

### ISSUE THREAD

**Issue by Mmrrtt92** [wooferzfg/tww-rando-tracker#853]
I don't believe this to be a real issue; but the Sunken Treasure for the "Reefs" apparently are tagged to need bombs. While this makes the job of getting them easier as you can remove the enemies [gunboats/turrets].  It is not absolutely needed to make the check. Just an thought to remove the requirement to make the check.

**Comment by wooferzfg** [comment]
The tracker's logic is based directly on the randomizer logic. In cases like this where an item isn't strictly necessary, I'd still prefer to show the randomizer's requirements, for the sake of consistency.
