### ISSUE TITLE
Paw Print Isle

### ISSUE THREAD

**Issue by rennsport** [wooferzfg/tww-rando-tracker#9]
For "Chuchu Cave - Scale the Wall" the tracker says the grappling hook is required, but it is actually the hookshot that is required.

**Comment by wooferzfg** [comment]
I think you're thinking of the wrong location? "Scale the Wall" is also inside the cave that has the 2 boulder chests + the main chest. It requires the Grappling Hook. "Wizzrobe Cave" is the one that requires the Hookshot.

Also, for future reference, the tracker loads the logic directly from the randomizer. If you think there's an issue with it, you should probably let LagoLunatic know instead.

**Comment by rennsport** [comment]
Ah if it is in the same area as the other 3 items than I was thinking of Wizzrobe Cave by mistake, sorry!
