### ISSUE TITLE
Add A Way To Disable Island Mappings

### ISSUE THREAD

**Issue by Grip555** [wooferzfg/tww-rando-tracker#909]
There's now giant text all over every island, to the point I can't even see how many areas I can check any more. I also can't even see the islands themselves any more over the text either.

<img width="273" alt="Ergh" src="https://user-images.githubusercontent.com/33988522/195751411-b8e73b53-ac74-4f80-8eca-fada82d7d6a3.png">

**Comment by wooferzfg** [comment]
Try doing Shift + F5 to refresh your tracker page. Also, if you loaded a save file, there might be some issues due to recent changes to the tracker code.

**Comment by Grip555** [comment]
That didn't change a thing. Also I started a new randomizer run yesterday, so do I really have to start all over again?

**Comment by wooferzfg** [comment]
You could run the old version of the tracker from the source code if you wanted to, or finish the run without the tracker. Unfortunately, I think those are your only options.
