### ISSUE TITLE
Expand "Clear All" button functionality to other locations

### ISSUE THREAD

**Issue by Mmrrtt92** [wooferzfg/tww-rando-tracker#983]
I turned on race mode and just a thought came through my head especially nice for hints that say "barren" or with race mode enabled if it doesn't have the blue icon on top of the dungeon necessary, we know that, that dungeon is barren. Having a "Middle click" or a button option to quickly check off every check that is in that areas checklist.

**Comment by wooferzfg** [comment]
There's already a "Clear All" button at the top of the dungeon locations list if you have Race Mode enabled.

**Comment by Mmrrtt92** [comment]
Didn't realize that it was already somewhat implemented, I was just thinking of a quicker way to click through things personally.

**Comment by wooferzfg** [comment]
Another way to implement this would be allowing the user to right click on a sector or extra location icon in order to clear all locations.

**Comment by wooferzfg** [comment]
Done in https://github.com/wooferzfg/tww-rando-tracker/commit/2850df0934a986ac0bd7fb0f303b51a537aff4ed and https://github.com/wooferzfg/tww-rando-tracker/commit/5f8e97fabad6ddcf5c78f688ea2898ec925955f8
